services:
  flask:
    image: seceng-project-flask
    container_name: seceng-project-flask
    build: .
    platform: linux/amd64
    ports:
     - "127.0.0.1:5000:5000"
    volumes:
     - .:/project
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=True
    command: flask --app src/app.py --debug run --host=0.0.0.0
    stdin_open: true
    tty: true